import type { GuidanceSet, LureType, NumericRange, PresentationProfile, SizeClass } from '../models/types'

const perchSizes:Record<SizeClass,NumericRange>={small:{min:3,max:5},medium:{min:5,max:8},large:{min:8,max:12}}
const terminalWeights={shallow:{min:1,max:4},medium:{min:4,max:8},deep:{min:8,max:15}} as const
const dropShotWeights={shallow:{min:4,max:8},medium:{min:8,max:15},deep:{min:15,max:25}} as const
const allVegetation=['none','edgeOrGaps','dense','unknown'] as const

const guidance=(slow:string,controlled:string,active:string):GuidanceSet=>({slow,controlled,active})
const presentation=(value:PresentationProfile)=>value

export const lures: LureType[] = [
  {
    id:'jig',label:'Softbait / Gummifisch',mounting:'Jigkopf',guidance:'Mit Grundkontakt in kurzen Sprüngen führen.',sizes:['small','medium','large'],depths:['shallow','medium','deep'],style:'bottom',priority:1,material:'soft',sizeRangesCm:perchSizes,
    presentations:[
      presentation({id:'jighead',label:'Jigkopf',mounting:'Offener Jigkopf; Gewicht so leicht wie kontrollierbar',depths:['shallow','medium','deep'],vegetation:['none','edgeOrGaps','unknown'],style:'bottom',weightKind:'terminal',terminalWeightByDepth:terminalWeights,guidance:guidance('Kurze, langsame Sprünge mit langen Grundpausen.','Mit reproduzierbarem Grundkontakt in kurzen Sprüngen führen.','Zügiger anjiggen, kontrolliert absinken lassen und die Fallphase nutzen.')}),
      presentation({id:'texas-offset',label:'Texas / Offset weedless',mounting:'Offsethaken mit gleitendem Bullet Weight, Hakenspitze weedless anlegen',depths:['shallow','medium','deep'],vegetation:['edgeOrGaps','dense'],style:'bottom',weightKind:'terminal',terminalWeightByDepth:terminalWeights,guidance:guidance('Sehr langsam durch Lücken ziehen und lange in Taschen pausieren.','Kontrolliert durch Krautgassen und an der Außenkante entlang führen.','Mit kurzen Impulsen aus dem Kraut lösen und in freie Taschen fallen lassen.')}),
      presentation({id:'carolina',label:'Carolina Rig',mounting:'Gleitgewicht vor Wirbel und Vorfach; Offsethaken am Softbait',depths:['shallow','medium','deep'],vegetation:['none','unknown'],style:'finesse',weightKind:'terminal',terminalWeightByDepth:dropShotWeights,guidance:guidance('Über offenen Grund schleifen und nach kurzen Wegen lange pausieren.','Mit konstantem Grundkontakt langsam über Sand, Kies oder die Kante ziehen.','In längeren Zügen suchen, danach den frei folgenden Köder absinken lassen.')}),
    ],
  },
  {id:'ned',label:'Ned Rig',mounting:'Pilzkopf, Gewicht an Tiefe angepasst',guidance:'Langsam schleifen und wiederholt stehen lassen.',sizes:['small','medium'],depths:['shallow','medium','deep'],style:'finesse',priority:2,material:'soft',sizeRangesCm:perchSizes,presentations:[presentation({id:'ned-head',label:'Ned Rig',mounting:'Pilzkopf; leichteste kontrollierbare Beschwerung',depths:['shallow','medium','deep'],vegetation:[...allVegetation],style:'finesse',weightKind:'terminal',terminalWeightByDepth:terminalWeights,guidance:guidance('Nur wenige Zentimeter bewegen und lange stehen lassen.','Langsam schleifen, kurz zittern und wiederholt pausieren.','Etwas zügiger hüpfen, aber jede Standphase bewusst ausfischen.')} )]},
  {id:'drop-shot',label:'Drop Shot',mounting:'Drop-Shot-Montage',guidance:'Am Platz fein zittern und lange pausieren.',sizes:['small','medium'],depths:['shallow','medium','deep'],style:'finesse',priority:3,material:'soft',sizeRangesCm:perchSizes,presentations:[presentation({id:'drop-shot',label:'Drop Shot',mounting:'Haken über dem Drop-Shot-Gewicht; Köderhöhe an Zielhorizont anpassen',depths:['shallow','medium','deep'],vegetation:[...allVegetation],style:'finesse',weightKind:'terminal',terminalWeightByDepth:dropShotWeights,guidance:guidance('Nahezu still halten, fein zittern und sehr lange pausieren.','Punktuell präsentieren und nur schrittweise versetzen.','Mit kurzen Impulsen Aufmerksamkeit erzeugen, dann wieder ruhig halten.')} )]},
  {id:'twitchbait',label:'Twitchbait',mounting:'Direkt am Karabiner',guidance:'Zweimal twitchen, dann deutlich pausieren.',sizes:['small','medium'],depths:['shallow','medium'],style:'search',priority:4,material:'hard',sizeRangesCm:perchSizes,presentations:[presentation({id:'suspending-hardbait',label:'Suspending Twitchbait',mounting:'Kleiner Rundbogen-Karabiner, ohne Zusatzbeschwerung',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:3,max:6},medium:{min:6,max:12}},guidance:guidance('Ein bis zwei sanfte Twitches, dann lange schwebend pausieren.','Zwei kontrollierte Twitches und eine deutliche Pause wiederholen.','Unregelmäßige Twitch-Serien mit kurzen Stopps und Richtungswechseln.')} )]},
  {id:'spinner',label:'Spinner',mounting:'Direkt am Karabiner',guidance:'Gleichmäßig und so langsam wie möglich einkurbeln.',sizes:['small','medium'],depths:['shallow','medium'],style:'search',priority:5,material:'metal',sizeRangesCm:perchSizes,presentations:[presentation({id:'inline-spinner',label:'Inline-Spinner',mounting:'Karabiner; bei Drall einen kleinen Wirbel vorschalten',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:3,max:6},medium:{min:6,max:12}},guidance:guidance('So langsam führen, dass das Blatt gerade sicher arbeitet.','Gleichmäßig durch das Zielband führen und die Blattarbeit kontrollieren.','Zügig fächerförmig suchen und mit kurzen Tempowechseln reizen.')} )]},
  {id:'crankbait',label:'Crankbait',mounting:'Direkt am Karabiner',guidance:'Gleichmäßig oder Stop-and-go in passender Lauftiefe führen.',sizes:['small','medium'],depths:['shallow','medium'],style:'search',priority:6,material:'hard',sizeRangesCm:perchSizes,presentations:[presentation({id:'diving-crank',label:'Crankbait in passender Lauftiefe',mounting:'Kleiner Rundbogen-Karabiner, keine Zusatzbeschwerung',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:4,max:8},medium:{min:8,max:16}},guidance:guidance('Langsam einkurbeln, Strukturkontakt lösen und lange Stopps setzen.','Gleichmäßig oder Stop-and-go in passender Lauftiefe führen.','Zügig Struktur und Tiefenband absuchen, kurze Stopps einstreuen.')} )]},
  {id:'chatterbait',label:'Chatterbait',mounting:'Direkt, optional mit Softbait-Trailer',guidance:'Gleichmäßig mit kurzen Tempowechseln führen.',sizes:['small','medium'],depths:['shallow','medium'],style:'search',priority:7,material:'hybrid',sizeRangesCm:perchSizes,presentations:[presentation({id:'bladed-jig',label:'Chatterbait',mounting:'Direkt am Karabiner, optional kompakter Softbait-Trailer',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:4,max:8},medium:{min:8,max:15}},guidance:guidance('Langsam und gleichmäßig, nur gelegentlich kurz beschleunigen.','Gleichmäßig mit kurzen Tempowechseln parallel zur Struktur führen.','Zügig suchen, aus Krautkontakt lösen und sofort weiterkurbeln.')} )]},
  {id:'blade-bait',label:'Blade Bait',mounting:'Direkt am Karabiner',guidance:'Kurz anheben und kontrolliert in den Zielhorizont absinken lassen.',sizes:['small','medium'],depths:['medium','deep'],style:'search',priority:8,material:'metal',sizeRangesCm:perchSizes,presentations:[presentation({id:'vibration-blade',label:'Blade Bait',mounting:'Karabiner am zur Laufstärke passenden Einhängepunkt',depths:['medium','deep'],vegetation:['none','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:5,max:10},medium:{min:10,max:18}},guidance:guidance('Nur kurz anheben, kontrolliert fallen lassen und lange am Grund pausieren.','Mit kurzen Lift-and-drop-Zügen im Zielhorizont führen.','Kräftiger anheben, kontrolliert absinken lassen und Strecke machen.')} )]},
  {id:'spinnerbait',label:'Spinnerbait',mounting:'Direkt am Karabiner',guidance:'Parallel zur Struktur gleichmäßig und kontrolliert führen.',sizes:['small','medium'],depths:['shallow','medium'],style:'search',priority:9,material:'hybrid',sizeRangesCm:perchSizes,presentations:[presentation({id:'perch-spinnerbait',label:'Spinnerbait',mounting:'Direkt am geschlossenen Bügel oder geeignetem Karabiner',depths:['shallow','medium'],vegetation:['edgeOrGaps','dense','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:4,max:8},medium:{min:8,max:15}},guidance:guidance('Langsam über Kraut und parallel zur Außenkante rollen.','Gleichmäßig durch freie Bahnen und entlang der Struktur führen.','Zügig über Deckung suchen und mit kurzen Richtungswechseln reizen.')} )]},
  {id:'popper',label:'Topwater / Popper',mounting:'Direkt am Karabiner',guidance:'Kurze Pop-Serien mit deutlichen Pausen an der Oberfläche.',sizes:['small','medium'],depths:['shallow'],style:'search',priority:10,material:'hard',sizeRangesCm:perchSizes,presentations:[presentation({id:'surface-popper',label:'Popper / Oberflächenköder',mounting:'Kleiner Rundbogen-Karabiner, keine Zusatzbeschwerung',depths:['shallow'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:3,max:7},medium:{min:7,max:14}},guidance:guidance('Ein einzelner Pop, dann lange ruhen lassen.','Kurze Pop-Serien mit deutlichen Pausen wiederholen.','Aktive Pop- oder Walk-Sequenzen mit kurzen Stopps über der Jagdzone.')} )]},
  {id:'tail-spinner',label:'Spinnertail / Tailspinner',mounting:'Direkt am Karabiner',guidance:'Auszählen, gleichmäßig führen oder per Lift-and-drop durch den Zielhorizont arbeiten.',sizes:['small','medium','large'],depths:['shallow','medium','deep'],style:'search',priority:11,material:'metal',sizeRangesCm:{small:{min:2.5,max:4},medium:{min:4,max:6.5},large:{min:6.5,max:9}},presentations:[presentation({id:'tail-spinner',label:'Spinnertail',mounting:'Karabiner; Lauf und Heckblatt vor dem ersten Wurf prüfen',depths:['shallow','medium','deep'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:5,max:10},medium:{min:10,max:18},large:{min:18,max:25}},guidance:guidance('Bis zum Zielhorizont zählen, sehr langsam einkurbeln oder kurz anheben und pausieren.','Sinkzeit messen, gleichmäßig führen oder kontrolliert per Lift-and-drop arbeiten.','Weit werfen, zügig mehrere Horizonte absuchen und Tempowechsel einbauen.')} )]},
]
