import type { GuidanceSet, LureType, NumericRange, PresentationProfile, SizeClass } from '../models/types'

const softSizes:Record<SizeClass,NumericRange>={small:{min:10,max:14},medium:{min:15,max:19},large:{min:20}}
const hardSizes:Record<SizeClass,NumericRange>={small:{min:8,max:12},medium:{min:12,max:16},large:{min:16,max:22}}
const allVegetation=['none','edgeOrGaps','dense','unknown'] as const
const guidance=(slow:string,controlled:string,active:string):GuidanceSet=>({slow,controlled,active})
const presentation=(value:PresentationProfile)=>value

export const pikeLures: LureType[] = [
  {
    id:'jig',label:'Hecht-Softbait / Gummifisch',mounting:'Hechtsicheres Vorfach, stabiler Jigkopf',guidance:'Kontrolliert mit Pausen durch das gewählte Tiefenband führen.',sizes:['small','medium','large'],depths:['shallow','medium','deep'],style:'bottom',priority:1,material:'soft',sizeRangesCm:softSizes,
    presentations:[
      presentation({id:'pike-weighted-rig',label:'Jigkopf / gewichtetes Rig',mounting:'Hechtsicheres Vorfach, stabiler Jigkopf oder belastbares Gewichtssystem mit Stinger',depths:['medium','deep'],vegetation:['none','edgeOrGaps','unknown'],style:'bottom',weightKind:'terminal',terminalWeightByDepth:{medium:{min:10,max:20},deep:{min:20,max:40}},guidance:guidance('Mit möglichst leichter Beschwerung langsam durch das Zielband führen und lange absinken lassen.','Kontrolliert mit Pausen durch den Horizont führen; Sinkzeit und Kontakt reproduzierbar halten.','Mit deutlichen Anzügen und kontrollierten Fallphasen aktiv suchen.')}),
      presentation({id:'pike-shallow-screw',label:'Shallow Screw Rig',mounting:'Hechtsicheres Vorfach, belastbare Shallow Screw und passend dimensionierter Stinger',depths:['shallow'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'none',guidance:guidance('Sehr langsam und nahezu unbeschwert über flache Zonen führen, lange Spinnstopps setzen.','Ruhig über Kraut und flache Deckung führen, regelmäßig pausieren.','Zügig über freie Bahnen suchen und mit kurzen Stopps absinken lassen.')}),
      presentation({id:'pike-weedless-offset',label:'Offset weedless',mounting:'Hechtsicheres Vorfach, extra starker Offsethaken und belastbare weedless Montage',depths:['shallow','medium'],vegetation:['edgeOrGaps','dense'],style:'search',weightKind:'terminal',terminalWeightByDepth:{shallow:{min:0,max:10},medium:{min:10,max:20}},guidance:guidance('Langsam durch Krauttaschen ziehen und in jeder freien Bahn pausieren.','Kontrolliert durch Lücken und entlang der Außenkante führen.','Mit kurzen Beschleunigungen aus dem Kraut lösen und in freie Taschen fallen lassen.')}),
    ],
  },
  {id:'jerkbait',label:'Jerkbait',mounting:'Hechtsicheres Vorfach, stabiler Karabiner',guidance:'Mit Schlägen und deutlichen Pausen über und neben Deckung führen.',sizes:['small','medium','large'],depths:['shallow','medium'],style:'search',priority:2,material:'hard',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-jerkbait',label:'Jerkbait / Glidebait',mounting:'Hechtsicheres Vorfach und belastbarer Rundbogen-Karabiner',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:20,max:40},medium:{min:40,max:70},large:{min:70,max:120}},guidance:guidance('Sanfte Schläge, danach lange schwebend oder langsam sinkend pausieren.','Mit kontrollierten Schlägen und deutlichen Pausen über und neben Deckung führen.','Aktive Schlagserien mit Richtungswechseln und kurzen Stopps.')} )]},
  {id:'crankbait',label:'Wobbler / Crankbait',mounting:'Hechtsicheres Vorfach, stabiler Karabiner',guidance:'In passender Lauftiefe gleichmäßig oder Stop-and-go führen.',sizes:['small','medium','large'],depths:['shallow','medium'],style:'search',priority:3,material:'hard',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-crankbait',label:'Wobbler / Crankbait',mounting:'Hechtsicheres Vorfach und belastbarer Rundbogen-Karabiner',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:15,max:35},medium:{min:35,max:65},large:{min:65,max:110}},guidance:guidance('Langsam in Lauftiefe bringen und mit langen Spinnstopps präsentieren.','Gleichmäßig oder Stop-and-go in passender Lauftiefe führen.','Zügig Strecke machen und mit kurzen Stopps Reaktionsbisse auslösen.')} )]},
  {id:'spinnerbait',label:'Spinnerbait',mounting:'Hechtsicheres Vorfach, direkt anbinden',guidance:'Parallel zu Kraut, Holz und freien Bahnen kontrolliert einkurbeln.',sizes:['small','medium','large'],depths:['shallow','medium'],style:'search',priority:4,material:'hybrid',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-spinnerbait',label:'Spinnerbait',mounting:'Hechtsicheres Vorfach, am geschlossenen Bügel direkt anbinden oder geeigneten Karabiner verwenden',depths:['shallow','medium'],vegetation:['edgeOrGaps','dense','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:15,max:30},medium:{min:30,max:60},large:{min:60,max:100}},guidance:guidance('So langsam führen, dass die Blätter sicher arbeiten, und Krautkanten lange ausfischen.','Parallel zu Kraut, Holz und freien Bahnen kontrolliert einkurbeln.','Zügig über Deckung suchen und mit kurzen Tempowechseln reizen.')} )]},
  {id:'spoon',label:'Blinker',mounting:'Hechtsicheres Vorfach mit Wirbel',guidance:'Gleichmäßig mit Tempowechseln und kurzen Absinkphasen führen.',sizes:['small','medium','large'],depths:['shallow','medium','deep'],style:'search',priority:5,material:'metal',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-spoon',label:'Blinker',mounting:'Hechtsicheres Vorfach, belastbarer Karabiner und Wirbel gegen Drall',depths:['shallow','medium','deep'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:15,max:30},medium:{min:30,max:60},large:{min:60,max:100}},guidance:guidance('Langsam taumeln lassen und lange kontrollierte Absinkphasen einbauen.','Gleichmäßig mit Tempowechseln und kurzen Absinkphasen führen.','Zügig suchen, abrupt stoppen und kontrolliert wieder anziehen.')} )]},
  {id:'spinner',label:'Spinner',mounting:'Hechtsicheres Vorfach mit Wirbel',guidance:'So langsam wie möglich mit sicher arbeitendem Blatt führen.',sizes:['small','medium','large'],depths:['shallow','medium'],style:'search',priority:6,material:'metal',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-spinner',label:'Großer Inline-Spinner',mounting:'Hechtsicheres Vorfach, belastbarer Karabiner und Wirbel gegen Drall',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:12,max:25},medium:{min:25,max:50},large:{min:50,max:90}},guidance:guidance('So langsam führen, dass das Blatt gerade sicher arbeitet.','Gleichmäßig entlang der Struktur und durch das Zielband führen.','Zügig fächerförmig suchen und kurze Tempowechsel einbauen.')} )]},
  {id:'swimbait',label:'Swimbait',mounting:'Hechtsicheres Vorfach, zur Tiefe passende Montage',guidance:'Ruhig und geradlinig durch den Zielhorizont führen.',sizes:['small','medium','large'],depths:['shallow','medium','deep'],style:'search',priority:7,material:'hard',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-swimbait',label:'Swimbait',mounting:'Hechtsicheres Vorfach und belastbarer Karabiner; keine zusätzliche Beschwerung ohne Herstellerfreigabe',depths:['shallow','medium','deep'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:20,max:45},medium:{min:45,max:80},large:{min:80,max:140}},guidance:guidance('Ruhig mit langen Pausen durch den Zielhorizont führen.','Geradlinig mit kontrollierten Spinnstopps präsentieren.','Aktiv Strecke machen, Tempo variieren und Richtungswechsel einbauen.')} )]},
  {id:'popper',label:'Topwater',mounting:'Hechtsicheres Vorfach, stabiler Karabiner',guidance:'Mit Pausen über freiem Flachwasser und Krautbahnen führen.',sizes:['small','medium','large'],depths:['shallow'],style:'search',priority:8,material:'hard',sizeRangesCm:hardSizes,presentations:[presentation({id:'pike-topwater',label:'Topwater',mounting:'Hechtsicheres Vorfach und belastbarer Rundbogen-Karabiner',depths:['shallow'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:20,max:40},medium:{min:40,max:70},large:{min:70,max:120}},guidance:guidance('Einzelne Impulse setzen und lange an der Oberfläche ruhen lassen.','Mit Pausen über freiem Flachwasser und Krautbahnen führen.','Aktive Walk- oder Pop-Sequenzen über bestätigter Oberflächenaktivität.')} )]},
  {id:'tailbait',label:'Tailbait',mounting:'Hechtsicheres Vorfach, stabiler Karabiner',guidance:'Langsam mit weiten Zügen und langen Pausen führen.',sizes:['small','medium','large'],depths:['shallow','medium'],style:'search',priority:9,material:'hybrid',sizeRangesCm:softSizes,presentations:[presentation({id:'pike-tailbait',label:'Tailbait',mounting:'Hechtsicheres Vorfach, belastbarer Karabiner und kontrollierte Haken-/Tail-Verbindung',depths:['shallow','medium'],vegetation:['none','edgeOrGaps','unknown'],style:'search',weightKind:'lure-total',lureWeightBySize:{small:{min:30,max:55},medium:{min:55,max:90},large:{min:90,max:140}},guidance:guidance('Sehr langsam mit weiten Zügen führen und nach jedem Zug lange pausieren.','Ruhig einholen, gelegentlich beschleunigen und den Tailbait kontrolliert stehen oder sinken lassen.','Mit variablen Zügen aktiv suchen, die Pausen aber klar beibehalten.')} )]},
]
