import { useState } from 'react'
import { Link,useLocation,useNavigate } from 'react-router-dom'
import { createRecommendationDecision } from '../../domain/engine/scoring'
import type { Conditions,ConfidenceMetric,Recommendation } from '../../domain/models/types'
import { useInventory } from '../inventory/useInventory'
import { sessionStore } from '../sessions/sessionStore'
import { useSessions } from '../sessions/useSessions'

const labels:Record<string,string>={small:'3–5 cm',medium:'5–8 cm',large:'8–12 cm',natural:'Naturdekor',contrast:'Dunkel/kontrastreich',transparent:'Transparent',ultralight:'Ultraleicht',light:'Leicht',heavy:'Schwer'}
const confidenceLabel=(level:ConfidenceMetric['level'])=>level==='high'?'Hoch':level==='medium'?'Mittel':'Niedrig'
function Summary({recommendation,label}:{recommendation:Recommendation;label:string}){return <article className="practical-summary"><span className="overline">{label}</span><h2>{recommendation.setup.lure.label}</h2><p>{recommendation.spot.spot.label} · {labels[recommendation.setup.size]} · {labels[recommendation.setup.color]}</p></article>}
function Confidence({title,metric}:{title:string;metric:ConfidenceMetric}){return <div className="confidence-metric"><span>{title}</span><strong className={`confidence ${metric.level}`}>{confidenceLabel(metric.level)} · {metric.value}%</strong><small>{metric.explanation}</small></div>}

export function RecommendationPage(){const conditions=useLocation().state as Conditions|null;const{inventory}=useInventory();const{activeSession,error}=useSessions();const navigate=useNavigate();const[openRanks,setOpenRanks]=useState<number[]>([1]);if(!conditions)return <section><h1>Keine Berechnung vorhanden</h1><p>Erfasse zuerst die Bedingungen am See.</p><Link className="primary" to="/neu">Bedingungen erfassen</Link></section>;const decision=createRecommendationDecision(conditions,inventory);const isAvailable=(recommendation:Recommendation)=>inventory.some(item=>item.lureTypeId===recommendation.setup.lure.id&&(conditions.targetFish==='perch'&&(!item.sizes||item.legacyPerch)||item.sizes?.includes(recommendation.setup.size)));const start=(recommendation:Recommendation)=>{const session=sessionStore.create(conditions,recommendation);if(session)navigate(`/session/${session.id}`)};const toggle=(rank:number)=>setOpenRanks(current=>current.includes(rank)?current.filter(item=>item!==rank):[...current,rank]);return <section>
  <p className="eyebrow">DEIN {conditions.targetFish==='pike'?'HECHT-':'BARSCH-'}PLAN AM SEE</p><h1>Fachlich bewertet. Praktisch gefiltert.</h1><p className="lead">Die Rangfolge entsteht ausschließlich aus den Bedingungen. Dein Bestand wird erst danach berücksichtigt.</p>
  {decision.hotWaterWarning&&<aside className="heat-warning"><strong>Hinweis bei sehr warmem Wasser</strong><p>{decision.hotWaterWarning}</p></aside>}
  <div className="practical-grid">{decision.practicalPrimary?<Summary recommendation={decision.practicalPrimary} label="BESTE VORHANDENE OPTION"/>:<article className="practical-summary warning"><span className="overline">BESTAND LEER</span><h2>Keine praktische Empfehlung</h2><p>Markiere zuerst mindestens einen Köder als vorhanden.</p></article>}{decision.bestMissing&&<Summary recommendation={decision.bestMissing} label="BESTE FEHLENDE OPTION"/>}</div>
  {decision.suitabilityWarning&&<p className="suitability-warning"><strong>Eignungshinweis:</strong> {decision.suitabilityWarning} Nutze die vorhandene Option bewusst als Kompromiss.</p>}<Link className="inventory-link" to="/bestand">Persönlichen Bestand bearbeiten →</Link>
  {error&&<p className="storage-error">{error}</p>}{activeSession&&<aside className="active-session-notice"><strong>Eine Session ist bereits aktiv.</strong><p>Beende sie, bevor du eine neue Empfehlung als Session startest.</p><Link to={`/session/${activeSession.id}`}>Aktive Session fortsetzen →</Link></aside>}
  <h2 className="ranking-title">Unveränderte fachliche Top 3</h2><aside className="metric-help"><p><strong>Eingabeabdeckung:</strong> Wie vollständig du die beobachtbare Situation beschrieben hast.</p><p><strong>Regel-Evidenz:</strong> Wie belastbar und passend die angewendeten Fachregeln sind.</p><small>Beide Werte sind keine Fangwahrscheinlichkeit.</small></aside><div className="recommendation-list">{decision.expertRanking.map(recommendation=>{const inInventory=isAvailable(recommendation);const open=openRanks.includes(recommendation.rank);const panelId=`recommendation-panel-${recommendation.rank}`;return <article className={`recommendation-card ${open?'expanded':''}`} key={`${recommendation.spot.spot.id}-${recommendation.setup.lure.id}`}><div className="recommendation-rank">0{recommendation.rank}</div><div className="recommendation-content">
    <div className="card-title"><div><span className="overline">{recommendation.spot.spot.label}</span><h2>{recommendation.setup.lure.label}</h2><div className="specs compact-specs"><span>{labels[recommendation.setup.size]}</span><span>{labels[recommendation.setup.weight]??'Mittel'}</span></div></div><span className={`inventory-status ${inInventory?'available':'missing'}`}>{inInventory?'Im Bestand':'Nicht im Bestand'}</span></div><button className="accordion-toggle" aria-expanded={open} aria-controls={panelId} onClick={()=>toggle(recommendation.rank)}>{open?'Details schließen':'Details anzeigen'} <span aria-hidden="true">{open?'−':'+'}</span></button>
    <div id={panelId} hidden={!open}>
    <div className="confidence-grid"><Confidence title="Eingabeabdeckung" metric={recommendation.inputCoverage}/><Confidence title="Regel-Evidenz" metric={recommendation.evidenceQuality}/></div>
    <div className="specs"><span>{labels[recommendation.setup.size]}</span><span>{labels[recommendation.setup.weight]??'Mittel'}</span></div><div className="color-guidance"><span className="overline">FARBE · {recommendation.colorGuidance.familyLabel}</span><div className="color-examples">{recommendation.colorGuidance.examples.map(example=><span key={example}>{example}</span>)}</div><p>{recommendation.colorGuidance.reason}</p></div><p><strong>Montage:</strong> {recommendation.setup.lure.mounting}</p><p><strong>Führung:</strong> {recommendation.setup.lure.guidance}</p>
    <div className="reason-box"><strong>Warum?</strong><ul>{recommendation.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>
    <div className="switch-plan"><strong>Wenn nichts beißt</strong>{recommendation.switchPlan.map((step,index)=><div className="switch-step" key={step.phase}><span>0{index+1}</span><div><h3>{step.title}</h3><p>{step.change}</p><small><b>{step.limit}</b> · {step.reason}</small></div></div>)}</div>{!inInventory&&<p className="missing-inventory-note">Dieser Köder ist nicht in deinem Bestand markiert. Du kannst den fachlichen Plan trotzdem als Session speichern.</p>}<button className="primary session-start" disabled={Boolean(activeSession)} onClick={()=>start(recommendation)}>Session mit dieser Empfehlung starten</button>
  </div></div></article>})}</div><Link className="secondary full" to="/neu">Bedingungen ändern</Link>
</section>}
