import { useMemo,useState } from 'react'
import { Link,useLocation,useNavigate } from 'react-router-dom'
import { createRecommendationDecision } from '../../domain/engine/scoring'
import { presentationForDisplay } from '../../domain/engine/presentation'
import type { Conditions,ConfidenceMetric,Recommendation } from '../../domain/models/types'
import { useInventory } from '../inventory/useInventory'
import { sessionStore } from '../sessions/sessionStore'
import { useSessions } from '../sessions/useSessions'
import { Icon } from '../../ui/components/Icon'

const confidenceLabel=(level:ConfidenceMetric['level'])=>level==='high'?'Hoch':level==='medium'?'Mittel':'Niedrig'
const sizeName={small:'Klein',medium:'Mittel',large:'Groß'} as const
function Summary({recommendation,label,primary=false}:{recommendation:Recommendation;label:string;primary?:boolean}){const presentation=presentationForDisplay(recommendation.setup);const measure=recommendation.setup.lure.material==='metal'?presentation.weightLabel:presentation.sizeLabel;return <article className={`practical-summary ${primary?'current-briefing':'terrain-alternative'}`}>{primary&&<div className="current-contours" aria-hidden="true"/>}<div><span className="overline">{label}</span><h2>{recommendation.setup.lure.label}</h2><p>{recommendation.spot.spot.label} · {measure} · {recommendation.colorGuidance.familyLabel}</p></div>{primary&&<span className="briefing-rank">0{recommendation.rank}</span>}</article>}
function Confidence({title,metric}:{title:string;metric:ConfidenceMetric}){return <div className="confidence-metric"><span>{title}</span><strong className={`confidence ${metric.level}`}>{confidenceLabel(metric.level)} · {metric.value}%</strong><small>{metric.explanation}</small></div>}

export function RecommendationPage(){const conditions=useLocation().state as Conditions|null;const{inventory,error:inventoryError}=useInventory();const{activeSession,error}=useSessions();const navigate=useNavigate();const[openRanks,setOpenRanks]=useState<number[]>([1]);const decision=useMemo(()=>conditions?createRecommendationDecision(conditions,inventory):undefined,[conditions,inventory]);if(!conditions||!decision)return <section className="page-shell empty-state"><h1>Keine Berechnung vorhanden</h1><p>Erfasse zuerst die Bedingungen am See.</p><Link className="primary" to="/neu">Bedingungen erfassen</Link></section>;const start=(recommendation:Recommendation)=>{const session=sessionStore.create(conditions,recommendation);if(session)navigate(`/session/${session.id}`)};const toggle=(rank:number)=>setOpenRanks(current=>current.includes(rank)?current.filter(item=>item!==rank):[...current,rank]);return <section className="page-shell recommendation-page">
  <p className="eyebrow">DEIN {conditions.targetFish==='pike'?'HECHT-':'BARSCH-'}PLAN AM SEE</p><h1>Deine vorhandenen Optionen.</h1><p className="lead">Die Reihenfolge enthält ausschließlich passende Köder aus deinem Bestand. Eine fachlich interessante Ergänzung steht separat darunter.</p>
  {decision.hotWaterWarning&&<aside className="heat-warning"><strong>Hinweis bei sehr warmem Wasser</strong><p>{decision.hotWaterWarning}</p></aside>}
  <div className="practical-grid">{decision.practicalPrimary?<Summary recommendation={decision.practicalPrimary} label="DEIN PLAN JETZT" primary/>:<article className="practical-summary warning"><span className="overline">KEINE DIREKTE OPTION</span><h2>Kein geeigneter vorhandener Köder</h2><p>Für Tiefe und Bedingungen ist aktuell kein passender Köder in deinem Bestand markiert.</p></article>}{decision.practicalAlternatives[0]&&<Summary recommendation={decision.practicalAlternatives[0]} label="VORHANDENE ALTERNATIVE"/>}</div>
  <Link className="inventory-link" to="/bestand">Persönlichen Bestand bearbeiten →</Link>
  {(error||inventoryError)&&<p className="storage-error">{error??inventoryError}</p>}{activeSession&&<aside className="active-session-notice"><strong>Eine Session ist bereits aktiv.</strong><p>Beende sie, bevor du eine neue Empfehlung als Session startest.</p><Link to={`/session/${activeSession.id}`}>Aktive Session fortsetzen →</Link></aside>}
  <h2 className="ranking-title">Deine vorhandenen Optionen</h2><aside className="metric-help"><p><strong>Eingabeabdeckung:</strong> Wie vollständig du die beobachtbare Situation beschrieben hast.</p><p><strong>Regel-Evidenz:</strong> Wie belastbar und passend die angewendeten validierten Fachregeln sind.</p><small>Es werden maximal drei unterschiedliche, tiefenkompatible Köder aus deinem Bestand gezeigt.</small></aside><div className="recommendation-list">{decision.practicalRanking.map((recommendation,index)=>{const open=openRanks.includes(recommendation.rank);const panelId=`recommendation-panel-${recommendation.rank}`;const presentation=presentationForDisplay(recommendation.setup);return <article className={`recommendation-card ${open?'expanded':''}`} key={`${recommendation.spot.spot.id}-${recommendation.setup.lure.id}`}><div className="recommendation-rank">0{index+1}</div><div className="recommendation-content">
    <div className="card-title"><div><span className="overline">{recommendation.spot.spot.label}</span><h2>{recommendation.setup.lure.label}</h2><div className="specs compact-specs"><span>{recommendation.setup.lure.material==='metal'?presentation.weightLabel:presentation.sizeLabel}</span><span>{presentation.profileLabel}</span></div></div><span className="inventory-status available">Im Bestand</span></div><button className="accordion-toggle" aria-expanded={open} aria-controls={panelId} onClick={()=>toggle(recommendation.rank)}>{open?'Details schließen':'Details anzeigen'} <Icon name="chevron-down"/></button>
    <div id={panelId} hidden={!open}>
    <div className="confidence-grid"><Confidence title="Eingabeabdeckung" metric={recommendation.inputCoverage}/><Confidence title="Regel-Evidenz" metric={recommendation.evidenceQuality}/></div>
    <div className="specs">{recommendation.setup.lure.material==='metal'?<><span>{presentation.weightLabel}</span><span>{presentation.sizeLabel}</span></>:<><span>{presentation.sizeLabel}</span><span>{presentation.weightLabel}</span></>}</div><div className="color-guidance"><span className="overline">FARBE · {recommendation.colorGuidance.familyLabel}</span><p><strong>Grundton:</strong> {recommendation.colorGuidance.baseLabel??recommendation.colorGuidance.familyLabel}<br/><strong>Finish:</strong> {recommendation.colorGuidance.finishLabel??'Passend zum Ködermaterial'}<br/><strong>Akzent:</strong> {recommendation.colorGuidance.accentLabel??'Kein fester Akzent'}</p><div className="color-examples">{recommendation.colorGuidance.examples.map(example=><span key={example}>{example}</span>)}</div><p>{recommendation.colorGuidance.reason}</p>{recommendation.colorGuidance.alternative&&<small>{recommendation.colorGuidance.alternative}</small>}</div><p><strong>Montage:</strong> {presentation.mounting}</p><p><strong>Führung:</strong> {presentation.guidance}</p>
    <div className="reason-box"><strong>Warum?</strong><ul>{recommendation.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>
    <div className="switch-plan"><strong>Wenn nichts beißt</strong>{recommendation.switchPlan.map((step,index)=><div className="switch-step" key={step.phase}><span>0{index+1}</span><div><h3>{step.title}</h3><p>{step.change}</p><small><b>{step.limit}</b> · {step.reason}</small></div></div>)}</div>{recommendation.inventoryFit&&!recommendation.inventoryFit.exact&&<p className="missing-inventory-note"><strong>Größenkompromiss:</strong> Fachlich bevorzugt wäre {sizeName[recommendation.inventoryFit.preferredSize]}; verwendet wird deine vorhandene Größe {sizeName[recommendation.inventoryFit.selectedSize]}.</p>}<button className="primary session-start" disabled={Boolean(activeSession)} onClick={()=>start(recommendation)}>Session mit dieser Empfehlung starten <Icon name="arrow-right"/></button>
  </div></div></article>})}</div>
  {decision.optionalLureTip&&<section className="optional-tips"><h2>Fachlich beste Ergänzung</h2><p className="lead">Diese Option ist nicht in deinem Bestand und gehört nicht zu deiner startbaren Top-Liste.</p><div className="practical-grid"><article className="practical-summary terrain-alternative"><span className="overline">NICHT IM BESTAND</span><h2>{decision.optionalLureTip.setup.lure.label}</h2><p>{decision.optionalLureTip.spot.spot.label} · {presentationForDisplay(decision.optionalLureTip.setup).sizeLabel} · {decision.optionalLureTip.colorGuidance.familyLabel}</p>{decision.optionalLureAdvantage&&decision.optionalLureAdvantage>0?<small>Diese Option liegt fachlich {decision.optionalLureAdvantage} Eignungspunkte vor deiner besten vorhandenen Wahl.</small>:<small>Eine zusätzliche fachliche Alternative für diese Situation.</small>}</article></div></section>}
  {decision.optionalSpotTip&&<section className="optional-tips"><h2>Optionaler Spot-Tipp</h2><p className="lead">Dieser Hinweis gehört nicht zu deinem aktuellen Plan.</p><div className="practical-grid"><article className="practical-summary terrain-alternative"><span className="overline">FALLS AM GEWÄSSER VORHANDEN</span><h2>{decision.optionalSpotTip.spot.spot.label}</h2><p>Diesen Bereich hast du nicht bestätigt. Prüfe ihn nur, wenn er tatsächlich erreichbar vorhanden ist.</p></article></div></section>}
  <Link className="secondary full" to="/neu">Bedingungen ändern</Link>
</section>}
