import {describe,expect,it} from 'vitest'
import {lures} from '../../domain/catalogs/lures'
import {pikeLures} from '../../domain/catalogs/pikeLures'
import {buildColorGuidance,preferredColorFamily} from '../../domain/engine/colorGuidance'
import {sizeLabelFor} from '../../domain/engine/presentation'
import {createRecommendationDecision,createRecommendations,evaluateSetups,evaluateSpots,isRecommendationAvailable} from '../../domain/engine/scoring'
import type {Conditions,InventoryItem,LureType} from '../../domain/models/types'
import {productSources} from '../../domain/research/productSources'
import {allRules} from '../../domain/rules/perchLakeRules'
import {pikeAllRules} from '../../domain/rules/pikeLakeRules'

const perch:Conditions={targetFish:'perch',waterType:'lake',season:'summer',timeOfDay:'day',turbidity:'slightly_turbid',depth:'medium',waterTemperature:'mild',light:'diffuse',activity:{status:'none',signs:[]},vegetation:'none',observedStructure:[]}
const pike:Conditions={...perch,targetFish:'pike',pikeSafetyConfirmed:true}
const setup=(conditions:Conditions,id:LureType['id'])=>{const spot=evaluateSpots(conditions)[0];return evaluateSetups(conditions,spot).find(item=>item.lure.id===id)!}

describe('produktive Quellenintegrität',()=>{
  it('löst jede Quellen-ID auf und verlangt ausschließlich Wissenschaft für Science-Regeln',()=>{for(const rule of [...allRules,...pikeAllRules]){for(const id of rule.sourceIds)expect(productSources[id],`${rule.id}: ${id}`).toBeDefined();if(rule.evidenceClass==='science'){expect(rule.sourceIds.length,rule.id).toBeGreaterThan(0);expect(rule.sourceIds.every(id=>productSources[id]?.evidenceType==='science'),rule.id).toBe(true)}}})
  it('enthält vollständige Metadaten und die korrigierten Hechtquellen',()=>{for(const source of Object.values(productSources)){expect(source.title).toBeTruthy();expect(source.authors).toBeTruthy();expect(source.year).toBeGreaterThan(1900);expect(()=>new URL(source.url)).not.toThrow();expect(source.scope).toBeTruthy();expect(source.lastVerifiedAt).toMatch(/^\d{4}-\d{2}-\d{2}$/)}for(const id of ['S03','S05','S07','S10','S11','S15','S16','S18','S20','S24'])expect(productSources[id],id).toBeDefined();expect(productSources.P01.url).toBe('https://doi.org/10.1016/j.fishres.2023.106621');expect(productSources.P01.authors).toContain('Niemi');expect(productSources.P02.authors).toContain('Nilsson');expect(productSources.P02.scope).toContain('Juvenile');expect(productSources.P05.evidenceType).toBe('experience');expect(productSources.P06.evidenceType).toBe('official-guidance');expect(pikeAllRules.filter(rule=>rule.sourceIds.some(id=>id==='P05'||id==='P06')).every(rule=>rule.evidenceClass==='experience')).toBe(true)})
})

describe('Köder- und Präsentationsmodell 2.0',()=>{
  it('enthält elf Barsch- und neun Hecht-Kategorien mit vollständigen Profilen',()=>{expect(lures).toHaveLength(11);expect(pikeLures).toHaveLength(9);for(const catalog of [lures,pikeLures]){expect(new Set(catalog.map(item=>item.id)).size).toBe(catalog.length);expect(catalog.every(item=>item.material&&item.sizeRangesCm&&item.presentations?.length&&item.presentations.every(profile=>profile.guidance.slow&&profile.guidance.controlled&&profile.guidance.active))).toBe(true)}})
  it('wählt Texas/Offset im Kraut und Carolina an offener Tiefenkante',()=>{const dense={...perch,depth:'shallow' as const,vegetation:'dense' as const};expect(setup(dense,'jig').resolvedPresentation?.profileId).toBe('texas-offset');const hard={...perch,season:'autumn' as const,depth:'deep' as const,vegetation:'none' as const,observedStructure:['dropoff' as const]};expect(setup(hard,'jig').resolvedPresentation?.profileId).toBe('carolina')})
  it('wählt beim Hecht Shallow Screw und weedless Offset',()=>{expect(setup({...pike,depth:'shallow'},'jig').resolvedPresentation?.profileId).toBe('pike-shallow-screw');expect(setup({...pike,depth:'shallow',vegetation:'dense'},'jig').resolvedPresentation?.profileId).toBe('pike-weedless-offset')})
  it('nennt in jedem Hechtprofil Vorfach und belastbare Verbindung',()=>{for(const lure of pikeLures){expect(lure.mounting,lure.id).toMatch(/hechtsicher/i);for(const profile of lure.presentations??[]){expect(profile.mounting,profile.id).toMatch(/hechtsicher/i);expect(profile.mounting,profile.id).toMatch(/belastbar|stabil|extra stark/i)}}})
  it('berücksichtigt Spinnertail im aktiven Herbst und wertet ihn im dichten Kraut ab',()=>{const active={...perch,season:'autumn' as const,depth:'deep' as const,waterTemperature:'cool' as const,activity:{status:'observed' as const,signs:['baitfish' as const]},observedStructure:['dropoff' as const]};expect(createRecommendations(active).map(item=>item.setup.lure.id)).toContain('tail-spinner');const openSpot=evaluateSpots(active)[0];const open=evaluateSetups(active,openSpot).find(item=>item.lure.id==='tail-spinner')!.score;const dense={...active,depth:'shallow' as const,vegetation:'dense' as const,observedStructure:[]};const denseSpot=evaluateSpots(dense).find(item=>item.spot.id==='vegetation')!;const closed=evaluateSetups(dense,denseSpot).find(item=>item.lure.id==='tail-spinner')!.score;expect(closed).toBeLessThan(open)})
  it('setzt Tailbait beim kalten Hecht mit langsamer Führung in die Top 3',()=>{const cold={...pike,season:'winter' as const,depth:'medium' as const,waterTemperature:'cold' as const,activity:{status:'none' as const,signs:[]}};const recommendations=createRecommendations(cold);expect(recommendations.map(item=>item.setup.lure.id)).toContain('tailbait');const tail=recommendations.find(item=>item.setup.lure.id==='tailbait')!;expect(tail.setup.resolvedPresentation?.mode).toBe('slow');expect(tail.setup.resolvedPresentation?.guidance).toMatch(/langsam|lange.*paus/i)})
  it('liefert artspezifische Größe und unterscheidet Beschwerung vom Gesamtgewicht',()=>{const perchJig=setup({...perch,depth:'shallow'},'jig').resolvedPresentation!;expect(perchJig.sizeLabel).toBe('5–8 cm');expect(perchJig.weightKind).toBe('terminal');expect(perchJig.weightLabel).toContain('1–4 g');const pikeTail=setup({...pike,waterTemperature:'cold'},'tailbait').resolvedPresentation!;expect(pikeTail.sizeLabel).toBe('15–19 cm');expect(pikeTail.weightKind).toBe('lure-total');expect(pikeTail.weightLabel).toContain('Ködergesamtgewicht');expect(sizeLabelFor(pikeLures.find(item=>item.id==='jig')!,'large')).toBe('20–25+ cm');expect(sizeLabelFor(pikeLures.find(item=>item.id==='jerkbait')!,'large')).toBe('16–22+ cm')})
  it('hält die neuen Köder in einer Szenariomatrix erreichbar, aber nicht dominant',()=>{const scenarios:Conditions[]=[perch,{...perch,season:'autumn',depth:'deep',waterTemperature:'cool',activity:{status:'observed',signs:['baitfish']},observedStructure:['dropoff']},{...perch,depth:'shallow',vegetation:'dense'},{...perch,season:'winter',waterTemperature:'cold'},pike,{...pike,season:'winter',waterTemperature:'cold'},{...pike,waterTemperature:'warm',activity:{status:'observed',signs:['pikeContact']},vegetation:'edgeOrGaps'},{...pike,depth:'shallow',vegetation:'dense'}];const topThree=scenarios.map(item=>createRecommendations(item).map(result=>result.setup.lure.id));expect(topThree.some(ids=>ids.includes('tail-spinner'))).toBe(true);expect(topThree.some(ids=>ids.includes('tailbait'))).toBe(true);expect(topThree.filter(ids=>ids.includes('tail-spinner')).length).toBeLessThan(scenarios.filter(item=>item.targetFish==='perch').length);expect(topThree.filter(ids=>ids.includes('tailbait')).length).toBeLessThan(scenarios.filter(item=>item.targetFish==='pike').length)})
})

describe('differenzierte Farbhilfe',()=>{
  it('nutzt Ghost für klare Hardbaits und materialgerechte Metallfarben',()=>{const twitch=lures.find(item=>item.id==='twitchbait')!;const clear={...perch,turbidity:'clear' as const,light:'bright' as const};expect(preferredColorFamily(clear,twitch)).toBe('transparent');expect(buildColorGuidance('transparent',clear,twitch).finishLabel).toMatch(/Ghost|transluzent/);const spinner=lures.find(item=>item.id==='spinner')!;expect(buildColorGuidance('natural',perch,spinner).examples).not.toContain('Green Pumpkin')})
  it('bevorzugt bei Nacht eine dunkle Silhouette ohne Fluoreszenzbonus',()=>{const lure=lures.find(item=>item.id==='crankbait')!;const guidance=buildColorGuidance('contrast',{...perch,timeOfDay:'night',light:'dark'},lure);expect(guidance.baseLabel).toContain('Dunkle');expect(guidance.accentLabel).toContain('Kein universeller Fluoreszenzbonus')})
  it('liefert bei trübem Wasser dunkle Silhouette und helle Gegenprobe',()=>{const lure=lures.find(item=>item.id==='jig')!;const guidance=buildColorGuidance('contrast',{...perch,turbidity:'turbid'},lure);expect(guidance.baseLabel).toMatch(/Dunkle.*Silhouette/);expect(guidance.alternative).toMatch(/helle.*Kontrastvariante/);expect(guidance.reason).toMatch(/keinen pauschalen Bonus/)})
  it('verändert Farbe weiterhin weder Reihenfolge noch Scores',()=>{const before=createRecommendations(perch).map(item=>[item.setup.lure.id,item.setup.score,item.spot.score]);buildColorGuidance('contrast',{...perch,turbidity:'turbid'},lures[0]);const after=createRecommendations(perch).map(item=>[item.setup.lure.id,item.setup.score,item.spot.score]);expect(after).toEqual(before)})
})

describe('artspezifische Bestandsprojektion',()=>{
  it('trennt gleichnamige Köder nach Fischart und verändert das Ranking nicht',()=>{const recommendation=createRecommendations(pike)[0];const perchOnly:InventoryItem[]=[{targetFish:'perch',lureTypeId:recommendation.setup.lure.id,sizes:[recommendation.setup.size]}];const pikeItem:InventoryItem[]=[{targetFish:'pike',lureTypeId:recommendation.setup.lure.id,sizes:[recommendation.setup.size]}];expect(isRecommendationAvailable(pike,perchOnly,recommendation)).toBe(false);expect(isRecommendationAvailable(pike,pikeItem,recommendation)).toBe(true);expect(createRecommendationDecision(pike,pikeItem).expertRanking).toEqual(createRecommendationDecision(pike,[]).expertRanking)})
})
