import {act,fireEvent,render,renderHook,screen} from '@testing-library/react'
import {beforeEach,describe,expect,it} from 'vitest'
import {MemoryRouter,Route,Routes} from 'react-router-dom'
import {createRecommendations} from '../../domain/engine/scoring'
import type {Conditions} from '../../domain/models/types'
import {useInventory} from '../../features/inventory/useInventory'
import {sessionStore} from '../../features/sessions/sessionStore'
import {SituationPage} from '../../features/situation/SituationPage'

describe('Hecht-Ablauf und artspezifischer Bestand v3',()=>{
  beforeEach(()=>localStorage.clear())
  it('blockiert die Hecht-Berechnung bis zur Sicherheitsbestätigung',()=>{render(<MemoryRouter initialEntries={['/neu/pike']}><Routes><Route path="/neu/:fish" element={<SituationPage/>}/><Route path="/empfehlung" element={<p>Ergebnis</p>}/></Routes></MemoryRouter>);const calculate=screen.getByRole('button',{name:/Drei Empfehlungen/});expect(calculate).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));expect(calculate).toBeEnabled();fireEvent.click(calculate);expect(screen.getByText('Ergebnis')).toBeInTheDocument()})
  it('migriert v1 verlustarm als prüfpflichtigen Barschbestand',()=>{localStorage.setItem('angelkompass.inventory.v1',JSON.stringify([{lureTypeId:'jig'},{lureTypeId:'spinner'},null]));const{result}=renderHook(()=>useInventory());expect(result.current.inventory).toEqual([{targetFish:'perch',lureTypeId:'jig',sizes:['small','medium','large'],migratedNeedsReview:true},{targetFish:'perch',lureTypeId:'spinner',sizes:['small','medium'],migratedNeedsReview:true}]);act(()=>result.current.toggleSize('perch','jig','large'));expect(result.current.inventory.find(item=>item.targetFish==='perch'&&item.lureTypeId==='jig')).toEqual({targetFish:'perch',lureTypeId:'jig',sizes:['small','medium'],migratedNeedsReview:false});expect(JSON.parse(localStorage.getItem('angelkompass.inventory.v3')!).schemaVersion).toBe(3);expect(localStorage.getItem('angelkompass.inventory.v1')).not.toBeNull()})
  it('migriert v2 artspezifisch und übernimmt Hecht nur mit expliziter Größe',()=>{localStorage.setItem('angelkompass.inventory.v2',JSON.stringify({schemaVersion:2,items:[{lureTypeId:'jig',sizes:['small','medium']},{lureTypeId:'spinner',legacyPerch:true}]}));const{result}=renderHook(()=>useInventory());expect(result.current.inventory).toEqual(expect.arrayContaining([{targetFish:'perch',lureTypeId:'jig',sizes:['small','medium'],migratedNeedsReview:true},{targetFish:'pike',lureTypeId:'jig',sizes:['medium'],migratedNeedsReview:true},{targetFish:'perch',lureTypeId:'spinner',sizes:['small','medium'],migratedNeedsReview:true}]));expect(result.current.inventory.some(item=>item.targetFish==='pike'&&item.lureTypeId==='spinner')).toBe(false)})
  it('kann artspezifisch alle Größen markieren und wieder entfernen',()=>{const{result}=renderHook(()=>useInventory());act(()=>result.current.toggleAllSizes('pike','jig'));expect(result.current.inventory).toContainEqual({targetFish:'pike',lureTypeId:'jig',sizes:['small','medium','large'],migratedNeedsReview:false});act(()=>result.current.toggleAllSizes('pike','jig'));expect(result.current.inventory.some(item=>item.targetFish==='pike'&&item.lureTypeId==='jig')).toBe(false)})
  it('verwirft beschädigte aktuelle Bestandsdaten ohne alte Schlüssel zu löschen',()=>{localStorage.setItem('angelkompass.inventory.v3','{kaputt');localStorage.setItem('angelkompass.inventory.v2',JSON.stringify({schemaVersion:2,items:[{lureTypeId:'jig',sizes:['medium']}]}));const{result}=renderHook(()=>useInventory());expect(result.current.inventory).toEqual([]);expect(localStorage.getItem('angelkompass.inventory.v2')).not.toBeNull()})
  it('speichert eine Hecht-Session als Ruleset-2.0-Snapshot',()=>{const conditions:Conditions={targetFish:'pike',waterType:'lake',season:'summer',timeOfDay:'day',turbidity:'clear',depth:'shallow',waterTemperature:'warm',light:'diffuse',activity:{status:'observed',signs:['baitfish']},vegetation:'edgeOrGaps',observedStructure:[],pikeSafetyConfirmed:true};sessionStore.resetForTests();const created=sessionStore.create(conditions,createRecommendations(conditions)[0]);expect(created?.rulesetVersion).toBe('pike-lake-2.0.0');expect(created?.recommendation.setup.resolvedPresentation).toBeDefined();expect(created?.conditions.pikeSafetyConfirmed).toBe(true)})
})
